### ISSUE TITLE
An item with the same key has already been added. Key: Gotenberg-Webhook-Extra-Http-Headers

### ISSUE THREAD

**Issue by naefp** [ChangemakerStudios/GotenbergSharpApiClient#39]
After updating to v2 it seems impossible to set multiple request headers to the webhook request.

usage:
```csharp
reqBuilder.AddWebhook(hook =>
  {
      hook.SetUrl(gotenbergWebHookUrl, HttpMethod.Post)
          .SetErrorUrl(gotenbergErrorUrl, HttpMethod.Post)
          .AddRequestHeader("JobId", jobId)
          .AddRequestHeader("DocumentId", documentId)
          .AddRequestHeader("ContentViewType", Enum.GetName(contentViewType));
  })
```

exception:
```
System.ArgumentException: An item with the same key has already been added. Key: Gotenberg-Webhook-Extra-Http-Headers
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Gotenberg.Sharp.API.Client.Domain.Builders.Faceted.WebhookBuilder.AddRequestHeader(String name, IEnumerable`1 values)
   at Gotenberg.Sharp.API.Client.Domain.Builders.Faceted.WebhookBuilder.AddRequestHeader(String name, String value)
```

It seems like the method AddRequestHeader should either accept an `IDictionary<string, string>` / `IDictionary<string, IEnumerable<string>>` or handle multiple calls of the method correctly. I didnt deep dive into the differences between v1 and v2 and not into differences between Gotenberg v6 and v7, but on the first view it seems to be a bug in GotenbergSharpApiClient. Or am I wrong?

**Comment by naefp** [comment]
OK I was not completly right, but as far I can see in the gotenberg docs:
`Gotenberg-Webhook-Extra-Http-Headers - the extra HTTP headers to send to both URLs (JSON format).`

and the sample:
`--header 'Gotenberg-Webhook-Extra-Http-Headers: {"MyHeader": "MyValue"}'`

..this header should be written as json dictionary.

Hope the changes in the PR are correct, I did not test it.

**Comment by naefp** [comment]
update:
I ve tested the webhook pattern with the dll from my fork and noticed another issue. In v7 gotenberg requires the webhook url to be sent as header instead of string content. This was not implemented yet in GotenbergSharp.

The second commit in my PR should theoretically solve this. And this time i tested a html conversion with webhook successfully. But I did not test other use cases...

hope it helps. :)
